logs:
  build: .
  links:
    - server
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: -h server -n local -p 28777
  privileged: true
harvester:
  image: temal/logio-harvester
  links: 
    - server
  volumes:
    - ./volumes:/home/logio/.log.io
    - /var/log:/var/log
    - ${LARAVEL_HOME}/Laravel/storage/logs:/var/log/laravel
server:
  image: temal/logio-server
  ports:
    - "28777:28777"
    - "28778:28778"
  volumes:
    - ./volumes:/home/logio/.log.io

